# dbt/models/marts/schema.yml
models:
  - name: fct_org_daily_activity
    description: "One row per organization per day aggregating all product activity"
    columns:
      - name: org_id
        tests:
          - not_null
          - unique_combination_of_columns:
              combination_of_columns:
                - org_id
                - activity_date
      
      - name: total_event_count
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000000
      
      - name: unique_user_count
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50000
      
      - name: activity_date
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: "dateadd(day, -365, current_date())"
              max_value: "current_date()"